-- 코드를 작성해주세요
select ED.ID, COALESCE(DD.CHILD_COUNT, 0) AS CHILD_COUNT
from ECOLI_DATA ED
LEFT JOIN (select PARENT_ID, count(*) AS CHILD_COUNT from ECOLI_DATA group by PARENT_ID) DD ON ED.ID = DD.PARENT_ID