-- 코드를 입력하세요
SELECT PD.PRODUCT_CODE, sum(OS.SALES_AMOUNT * PD.PRICE) AS SALES
from PRODUCT PD
right join OFFLINE_SALE OS on PD.PRODUCT_ID = OS.PRODUCT_ID
group by PD.PRODUCT_ID, PD.PRICE
order by SALES DESC, PD.PRODUCT_CODE ASC;