-- 코드를 입력하세요
select P.PRODUCT_CODE, sum(P.PRICE * O.SALES_AMOUNT) AS SALES
from PRODUCT P
right join OFFLINE_SALE O
on P.PRODUCT_ID = O.PRODUCT_ID
group by P.PRODUCT_ID, P.PRICE
order by SALES DESC, P.PRODUCT_CODE ASC;





