-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
from MEMBER_PROFILE
where 1=1
and MONTH(DATE_OF_BIRTH) = 3
and GENDER = 'W'
and TLNO is not NULL
order by MEMBER_ID ASC;