-- 코드를 작성해주세요
select FI.ID, FNI.FISH_NAME, FI.LENGTH
from FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
where FI.LENGTH = (select MAX(LENGTH) from FISH_INFO where FISH_TYPE = FI.FISH_TYPE)
order by FI.ID ASC;
